// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApEkl0XwmeRxs7BvhNiUgWBp79WwCada4',
    appId: '1:34061023916:android:your-android-app-id',
    messagingSenderId: '34061023916',
    projectId: 'vet2u-clinic-app',
    storageBucket: 'vet2u-clinic-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApEkl0XwmeRxs7BvhNiUgWBp79WwCada4',
    appId: '1:34061023916:ios:your-ios-app-id',
    messagingSenderId: '34061023916',
    projectId: 'vet2u-clinic-app',
    storageBucket: 'vet2u-clinic-app.firebasestorage.app',
    iosBundleId: 'com.example.clinicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your-macos-api-key',
    appId: 'your-macos-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
    iosBundleId: 'com.example.clinic_app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApEkl0XwmeRxs7BvhNiUgWBp79WwCada4',
    appId: '1:34061023916:web:2babd4237dc57d6c3efd09',
    messagingSenderId: '34061023916',
    projectId: 'vet2u-clinic-app',
    authDomain: 'vet2u-clinic-app.firebaseapp.com',
    storageBucket: 'vet2u-clinic-app.firebasestorage.app',
    measurementId: 'G-VHSKQX2TRC',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'your-windows-api-key',
    appId: 'your-windows-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
  );
}
