// File generated by FlutterFire CLI.
// ignore_for_file: type=lint, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
/// To update these values, run:
/// dart pub global run flutterfire configure
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Android configuration
  /// Get these from Firebase Console → Project Settings → Your apps → Android
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApEkl0XwmeRxs7BvhNiUgWBp79WwCada4',
    appId: '1:34061023916:android:68e3c4e0b1c8c2cf3efd09',
    messagingSenderId: '34061023916',
    projectId: 'vet2u-clinic-app',
    storageBucket: 'vet2u-clinic-app.firebasestorage.app',
  );

  /// iOS configuration
  /// Get these from Firebase Console → Project Settings → Your apps → iOS
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApEkl0XwmeRxs7BvhNiUgWBp79WwCada4',
    appId: '1:34061023916:ios:68e3c4e0b1c8c2cf3efd09',
    messagingSenderId: '34061023916',
    projectId: 'vet2u-clinic-app',
    storageBucket: 'vet2u-clinic-app.firebasestorage.app',
    iosBundleId: 'com.example.clinicApp',
  );

  /// macOS configuration
  /// Get these from Firebase Console → Project Settings → Your apps → macOS
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApEkl0XwmeRxs7BvhNiUgWBp79WwCada4',
    appId: '1:34061023916:macos:68e3c4e0b1c8c2cf3efd09',
    messagingSenderId: '34061023916',
    projectId: 'vet2u-clinic-app',
    storageBucket: 'vet2u-clinic-app.firebasestorage.app',
    iosBundleId: 'com.example.clinic_app',
  );

  /// Web configuration
  /// Get these from Firebase Console → Project Settings → Your apps → Web
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApEkl0XwmeRxs7BvhNiUgWBp79WwCada4',
    authDomain: 'vet2u-clinic-app.firebaseapp.com',
    projectId: 'vet2u-clinic-app',
    storageBucket: 'vet2u-clinic-app.firebasestorage.app',
    messagingSenderId: '34061023916',
    appId: '1:34061023916:web:68e3c4e0b1c8c2cf3efd09',
    measurementId: 'G-VHSKQX2TRC',
  );

  /// Windows configuration
  /// Get these from Firebase Console → Project Settings → Your apps → Windows
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApEkl0XwmeRxs7BvhNiUgWBp79WwCada4',
    authDomain: 'vet2u-clinic-app.firebaseapp.com',
    projectId: 'vet2u-clinic-app',
    storageBucket: 'vet2u-clinic-app.firebasestorage.app',
    messagingSenderId: '34061023916',
    appId: '1:34061023916:web:68e3c4e0b1c8c2cf3efd09',
  );
}
